In [2]:
import pandas as pd
import numpy as np
from scipy import stats
import matplotlib.pyplot as plt
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler

In [28]:
#splitting pre normalised data year wise
data=pd.read_csv('data.csv')

states=list(['Andhra Pradesh','Arunachal Pradesh','Assam','Bihar','Chhattisgarh','Goa','Gujarat','Haryana','Himachal Pradesh','Jammu & Kashmir','Jharkhand','Karnataka','Kerala','Madhya Pradesh','Maharashtra','Manipur','Meghalaya','Mizoram','Nagaland','Odisha','Punjab','Rajasthan','Sikkim','Tamil Nadu','Tripura','Uttar Pradesh','Uttarakhand','West Bengal','A&N Islands','Chandigarh','D&N Haveli','Daman & Diu','Delhi UT','Lakshadweep','Puducherry','All India'])

for year in range(2001,2013):
    yy=str(year)
#     yy='2001'
    eachyear=data[['STATE/UT','CRIME HEAD',yy]]
    eachyear=eachyear.set_index('STATE/UT')    
    eachyear=eachyear.set_index('CRIME HEAD').groupby(level=0).apply(lambda x : np.concatenate(x.values.tolist())).apply(pd.Series)
    eachyear.columns=states

    eachyear=eachyear.T
    eachyear=eachyear.drop('All India')
    eachyear=eachyear.drop('TOTAL CRIMES AGAINST WOMEN',axis=1)
    eachyear
    eachyear.to_csv(('DATA'+yy+'.csv'))

    testdata=pd.read_csv(('DATA'+yy+'.csv'))
    testdata=testdata.rename(index=str,columns={'Unnamed: 0':'STATE/UT'})
    testdata.to_csv(('DATA'+yy+'.csv'),index=False)

In [33]:
# merging all years
import pandas as pd
import glob

path = 'normalisedallyears' # use your path
all_files = glob.glob(path + "/*.csv")

li = []

for filename in all_files:
    df = pd.read_csv(filename, index_col=None, header=0)
    li.append(df)

frame = pd.concat(li, axis=0, ignore_index=True)
frame=frame.drop('STATE/UT',axis=1)
frame.to_csv('categorised_crime.csv',index=False)

## Applying spearman corelation on categorised crime

In [34]:
data=pd.read_csv("categorised_crime.csv")
data.T
cr,p=stats.spearmanr(data)
corelation=pd.DataFrame(cr)
corelation.to_csv('correlation_post_normalization.csv')

In [140]:
array=

array([[16075, 14645,  6851, 34124,  9746, 49170,  8796,  1052],
       [16075, 14645,  6851, 34124,  9746, 49170,  8796,  1052]])

In [141]:
array.shape

(2, 8)

In [158]:
cr,p=stats.spearmanr(data)

In [163]:
corelation=pd.DataFrame(cr)

In [165]:
corelation.to_csv('corelation.csv')

## finding PCA on 2001 data

In [277]:
data2001=pd.read_csv("DATA_perlakh_2001.csv")


states=data2001['STATE/UT']
x=data2001.drop('STATE/UT',axis=1)
features=list(x.columns)
x = StandardScaler().fit_transform(x)
pd.DataFrame(data=x,columns=features)
pca = PCA(n_components=2)
principalComponents = pca.fit_transform(x)
principalDf = pd.DataFrame(data = principalComponents, columns = ['principal component 1', 'principal component 2'])
principalDf.insert(loc=0,column='STATE/UT',value=data2001['STATE/UT'],)
principalDf.to_csv("principal_components_2001.csv")

# altering FemalePopulation to suite our need

In [59]:
# femalePopulation=pd.read_csv('FemalePopulation.csv')
# femalePopulation.T.to_csv('FemalePopulation.csv')

In [120]:
femalePopulation=pd.read_csv('FemalePopulation.csv')
# femalePopulation= femalePopulation.sort_values('STATE/UT')
femalePopulation

,STATE/UT,2001,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012
0,A&N Islands,163,165,169,174,181,188,196,205,215,224,233,241
1,Andhra Pradesh,37683,38179,38660,39129,39587,40036,40474,40900,41316,41724,42124,42517
2,Arunachal Pradesh,518,525,532,539,546,553,560,567,573,580,587,594
3,Assam,12878,13090,13298,13501,13702,13902,14099,14294,14486,14678,14870,15061
4,Bihar,39755,40548,41328,42094,42847,43586,44312,45025,45724,46409,47080,47738
5,Chandigarh,394,400,412,430,450,471,495,522,550,579,606,632
6,Chhattisgarh,10360,10544,10725,10902,11076,11249,11419,11587,11753,11917,12081,12244
7,D&N Haveli,99,94,94,97,103,109,117,127,139,150,160,169
8,Daman & Diu,66,71,75,79,82,85,88,89,91,93,95,97
9,Delhi UT,6243,6428,6612,6799,6990,7186,7386,7590,7798,8013,8235,8465
10,Goa,660,658,666,680,697,716,737,763,791,818,841,862
11,Gujarat,24285,24684,25076,25463,25844,26220,26590,26954,27313,27667,28016,28359
12,Haryana,9781,9975,10169,10362,10555,10746,10936,11125,11313,11500,11685,11869
13,Himachal Pradesh,2990,3027,3063,3098,3132,3166,3199,3231,3262,3293,3322,3351
14,Jammu & Kashmir,4783,4862,4943,5024,5105,5185,5265,5345,5424,5502,5579,5654
15,Jharkhand,13061,13304,13538,13766,13990,14211,14429,14642,14852,15062,15274,15486
16,Karnataka,25952,26312,26664,27010,27350,27685,28015,28338,28656,28969,29278,29583
17,Kerala,16373,16517,16660,16801,16939,17074,17206,17336,17462,17585,17704,17819
18,Lakshadweep,30,32,33,34,35,36,37,37,37,38,38,39
19,Madhya Pradesh,28904,29490,30069,30641,31209,31773,32332,32886,33436,33982,34527,35069
20,Maharashtra,46478,47214,47956,48701,49444,50181,50916,51651,52382,53105,53816,54519
21,Manipur,1071,1086,1100,1114,1129,1143,1157,1171,1186,1200,1214,1229
22,Meghalaya,1143,1158,1173,1189,1204,1219,1234,1250,1265,1280,1296,1311
23,Mizoram,429,435,441,447,452,458,464,470,475,481,487,493
24,Nagaland,943,956,968,981,993,1006,1019,1031,1044,1056,1069,1082
25,Odisha,18144,18365,18580,18789,18994,19196,19393,19586,19776,19963,20148,20330
26,Puducherry,487,489,498,512,529,547,567,590,615,640,661,681
27,Punjab,11374,11520,11667,11814,11960,12104,12245,12386,12525,12661,12792,12920
28,Rajasthan,27087,27633,28181,28728,29272,29811,30345,30877,31405,31925,32436,32938
29,Sikkim,252,255,259,262,266,269,273,276,280,284,287,291
30,Tamil Nadu,31005,31304,31593,31872,32142,32405,32658,32903,33140,33369,33592,33808
31,Tripura,1557,1578,1599,1620,1640,1661,1682,1703,1724,1744,1765,1786
32,Uttar Pradesh,78633,80211,81812,83431,85060,86693,88335,89989,91650,93311,94966,96618
33,Uttarakhand,4163,4234,4306,4377,4449,4520,4591,4662,4732,4802,4871,4939
34,West Bengal,38710,39269,39798,40303,40791,41268,41731,42174,42605,43029,43454,43874

states1=np.array(femalePopulation['STATE/UT'])
states1

for a,b in zip(states,states1):
    print(a," - ",b)

femalePopulation.replace(to_replace=states1,value=states,inplace=True)

femalePopulation.to_csv('FemalePopulation.csv')

# data normalization

In [257]:
data=pd.read_csv('data.csv')
data

,STATE/UT,CRIME HEAD,2001,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012
0,Andhra Pradesh,RAPE,871,1002,946,1016,935,1049,1070,1257,1188,1362,1442,1341
1,Arunachal Pradesh,RAPE,33,38,31,42,35,37,48,42,59,47,42,46
2,Assam,RAPE,817,970,1095,1171,1238,1244,1437,1438,1631,1721,1700,1716
3,Bihar,RAPE,888,1040,985,1390,1147,1232,1555,1302,929,795,934,927
4,Chhattisgarh,RAPE,959,992,898,969,990,995,982,978,976,1012,1053,1034
5,Goa,RAPE,12,12,31,37,20,21,20,30,47,36,29,55
6,Gujarat,RAPE,286,267,236,339,324,354,316,374,433,408,439,473
7,Haryana,RAPE,398,361,353,386,461,608,488,631,603,720,733,668
8,Himachal Pradesh,RAPE,124,137,126,153,141,113,159,157,183,160,168,183
9,Jammu & Kashmir,RAPE,169,192,211,218,201,250,288,219,237,245,277,303
10,Jharkhand,RAPE,567,797,712,797,753,799,855,791,719,773,784,812
11,Karnataka,RAPE,293,292,321,291,343,400,436,446,509,586,636,621
12,Kerala,RAPE,562,499,394,480,478,601,512,568,568,634,1132,1019
13,Madhya Pradesh,RAPE,2851,2891,2738,2875,2921,2900,3010,2937,2998,3135,3406,3425
14,Maharashtra,RAPE,1302,1352,1268,1388,1545,1500,1451,1558,1483,1599,1701,1839
15,Manipur,RAPE,20,14,18,31,25,40,20,38,31,34,53,63
16,Meghalaya,RAPE,26,38,40,54,63,74,82,88,112,149,130,164
17,Mizoram,RAPE,52,76,54,20,37,72,83,77,83,92,77,103
18,Nagaland,RAPE,17,17,14,18,17,23,13,19,22,16,23,21
19,Odisha,RAPE,790,691,725,770,799,985,939,1113,1023,1025,1112,1458
20,Punjab,RAPE,298,299,380,390,398,442,519,517,511,546,479,680
21,Rajasthan,RAPE,1049,1051,1050,1038,993,1085,1238,1355,1519,1571,1800,2049
22,Sikkim,RAPE,8,6,10,3,18,20,24,20,18,18,16,34
23,Tamil Nadu,RAPE,423,534,557,618,571,457,523,573,596,686,677,737
24,Tripura,RAPE,102,108,114,160,162,189,157,204,190,238,205,229
25,Uttar Pradesh,RAPE,1958,1415,911,1397,1217,1314,1648,1871,1759,1563,2042,1963
26,Uttarakhand,RAPE,74,89,107,115,133,147,117,87,111,121,129,148
27,West Bengal,RAPE,709,759,1002,1475,1686,1731,2106,2263,2336,2311,2363,2046
28,A&N Islands,RAPE,3,2,2,10,4,6,3,12,18,24,13,12
29,Chandigarh,RAPE,18,18,18,19,33,19,22,20,29,31,27,27
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
294,Gujarat,TOTAL CRIMES AGAINST WOMEN,5805,5373,5735,6211,6343,7279,8260,8616,8009,8148,8815,9561
295,Haryana,TOTAL CRIMES AGAINST WOMEN,3393,4385,4170,4276,4161,4617,4645,5142,5312,5562,5491,6002
296,Himachal Pradesh,TOTAL CRIMES AGAINST WOMEN,890,838,729,823,793,792,1018,979,954,1028,997,912
297,Jammu & Kashmir,TOTAL CRIMES AGAINST WOMEN,1656,2016,2164,2208,2144,2432,2521,2295,2624,2611,3146,3328
298,Jharkhand,TOTAL CRIMES AGAINST WOMEN,2229,2490,2488,2490,2544,2979,3317,3183,3021,3087,3132,4536
299,Karnataka,TOTAL CRIMES AGAINST WOMEN,6002,6170,5834,5423,6057,6084,6569,6891,7852,8807,9594,10366
300,Kerala,TOTAL CRIMES AGAINST WOMEN,5450,5829,5653,6483,6762,7554,7837,8117,8049,9463,11288,10930
301,Madhya Pradesh,TOTAL CRIMES AGAINST WOMEN,14549,15260,14547,15203,14529,14321,15370,14908,15827,16468,16599,16832
302,Maharashtra,TOTAL CRIMES AGAINST WOMEN,12524,11322,11273,12169,13370,14452,14924,15862,15048,15737,15728,16353
303,Manipur,TOTAL CRIMES AGAINST WOMEN,112,170,137,134,140,171,188,211,194,190,247,304
304,Meghalaya,TOTAL CRIMES AGAINST WOMEN,66,71,69,113,131,176,172,208,237,261,269,255
305,Mizoram,TOTAL CRIMES AGAINST WOMEN,126,154,147,91,95,125,151,162,150,170,167,199
306,Nagaland,TOTAL CRIMES AGAINST WOMEN,30,26,25,30,37,43,32,47,46,41,38,51
307,Odisha,TOTAL CRIMES AGAINST WOMEN,5357,4779,4946,5239,6249,6825,7304,8303,8120,8501,9433,11988
308,Punjab,TOTAL CRIMES AGAINST WOMEN,2361,2295,2375,1955,1969,2242,2694,2627,2631,2853,2641,3238
309,Rajasthan,TOTAL CRIMES AGAINST WOMEN,12175,12049,11812,13127,11657,12934,14270,14491,17316,18182,19888,21106
310,Sikkim,TOTAL CRIMES AGAINST WOMEN,24,28,37,49,62,47,55,48,41,42,55,68
311,Tamil Nadu,TOTAL CRIMES AGAINST WOMEN,10111,9798,8888,9332,8648,6489,7811,7220,6051,6708,6940,7192
312,Tripura,TOTAL CRIMES AGAINST WOMEN,438,536,537,670,840,964,1067,1416,1517,1678,1358,1559
313,Uttar Pradesh,TOTAL CRIMES AGAINST WOMEN,20227,15647,12840,15485,14875,16375,20993,23569,23254,20169,22639,23569
314,Uttarakhand,TOTAL CRIMES AGAINST WOMEN,749,870,886,988,786,1038,1097,1151,1188,1074,996,1067
315,West Bengal,TOTAL CRIMES AGAINST WOMEN,6570,6842,8508,11047,11887,12785,16544,20912,23307,26125,29133,30942
316,A&N Islands,TOTAL CRIMES AGAINST WOMEN,34,27,22,27,22,36,56,80,92,85,51,49
317,Chandigarh,TOTAL CRIMES AGAINST WOMEN,150,189,159,188,205,224,230,143,150,141,156,241
318,D&N Haveli,TOTAL CRIMES AGAINST WOMEN,19,15,13,22,24,32,18,28,20,30,18,16
319,Daman & Diu,TOTAL CRIMES AGAINST WOMEN,10,8,10,7,10,9,11,15,13,14,11,11
320,Delhi UT,TOTAL CRIMES AGAINST WOMEN,2291,2216,3282,3677,4351,4544,4804,3938,4251,4518,5234,5959
321,Lakshadweep,TOTAL CRIMES AGAINST WOMEN,0,2,4,1,0,1,5,4,1,1,0,2
322,Puducherry,TOTAL CRIMES AGAINST WOMEN,119,141,121,110,127,149,179,129,106,115,89,61
323,TOTAL Crime against Women,TOTAL CRIMES AGAINST WOMEN,143795,143034,140601,154333,155553,164765,185312,195857,203804,213585,228650,244270

In [123]:
femalePopulation

,STATE/UT,2001,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012
0,A&N Islands,163,165,169,174,181,188,196,205,215,224,233,241
1,Andhra Pradesh,37683,38179,38660,39129,39587,40036,40474,40900,41316,41724,42124,42517
2,Arunachal Pradesh,518,525,532,539,546,553,560,567,573,580,587,594
3,Assam,12878,13090,13298,13501,13702,13902,14099,14294,14486,14678,14870,15061
4,Bihar,39755,40548,41328,42094,42847,43586,44312,45025,45724,46409,47080,47738
5,Chandigarh,394,400,412,430,450,471,495,522,550,579,606,632
6,Chhattisgarh,10360,10544,10725,10902,11076,11249,11419,11587,11753,11917,12081,12244
7,D&N Haveli,99,94,94,97,103,109,117,127,139,150,160,169
8,Daman & Diu,66,71,75,79,82,85,88,89,91,93,95,97
9,Delhi UT,6243,6428,6612,6799,6990,7186,7386,7590,7798,8013,8235,8465
10,Goa,660,658,666,680,697,716,737,763,791,818,841,862
11,Gujarat,24285,24684,25076,25463,25844,26220,26590,26954,27313,27667,28016,28359
12,Haryana,9781,9975,10169,10362,10555,10746,10936,11125,11313,11500,11685,11869
13,Himachal Pradesh,2990,3027,3063,3098,3132,3166,3199,3231,3262,3293,3322,3351
14,Jammu & Kashmir,4783,4862,4943,5024,5105,5185,5265,5345,5424,5502,5579,5654
15,Jharkhand,13061,13304,13538,13766,13990,14211,14429,14642,14852,15062,15274,15486
16,Karnataka,25952,26312,26664,27010,27350,27685,28015,28338,28656,28969,29278,29583
17,Kerala,16373,16517,16660,16801,16939,17074,17206,17336,17462,17585,17704,17819
18,Lakshadweep,30,32,33,34,35,36,37,37,37,38,38,39
19,Madhya Pradesh,28904,29490,30069,30641,31209,31773,32332,32886,33436,33982,34527,35069
20,Maharashtra,46478,47214,47956,48701,49444,50181,50916,51651,52382,53105,53816,54519
21,Manipur,1071,1086,1100,1114,1129,1143,1157,1171,1186,1200,1214,1229
22,Meghalaya,1143,1158,1173,1189,1204,1219,1234,1250,1265,1280,1296,1311
23,Mizoram,429,435,441,447,452,458,464,470,475,481,487,493
24,Nagaland,943,956,968,981,993,1006,1019,1031,1044,1056,1069,1082
25,Odisha,18144,18365,18580,18789,18994,19196,19393,19586,19776,19963,20148,20330
26,Puducherry,487,489,498,512,529,547,567,590,615,640,661,681
27,Punjab,11374,11520,11667,11814,11960,12104,12245,12386,12525,12661,12792,12920
28,Rajasthan,27087,27633,28181,28728,29272,29811,30345,30877,31405,31925,32436,32938
29,Sikkim,252,255,259,262,266,269,273,276,280,284,287,291
30,Tamil Nadu,31005,31304,31593,31872,32142,32405,32658,32903,33140,33369,33592,33808
31,Tripura,1557,1578,1599,1620,1640,1661,1682,1703,1724,1744,1765,1786
32,Uttar Pradesh,78633,80211,81812,83431,85060,86693,88335,89989,91650,93311,94966,96618
33,Uttarakhand,4163,4234,4306,4377,4449,4520,4591,4662,4732,4802,4871,4939
34,West Bengal,38710,39269,39798,40303,40791,41268,41731,42174,42605,43029,43454,43874

In [125]:
data.loc[data['CRIME HEAD']=='TOTAL CRIMES AGAINST WOMEN']

,STATE/UT,CRIME HEAD,2001,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012
288,Andhra Pradesh,TOTAL CRIMES AGAINST WOMEN,16477,18880,18382,18921,20819,21484,24738,24111,25569,27244,28246,28171
289,Arunachal Pradesh,TOTAL CRIMES AGAINST WOMEN,180,159,139,148,150,168,185,175,164,190,171,201
290,Assam,TOTAL CRIMES AGAINST WOMEN,4243,5092,5312,5700,6027,6801,6844,8122,9721,11555,11503,13544
291,Bihar,TOTAL CRIMES AGAINST WOMEN,5356,5743,5900,8091,6019,6740,7548,8662,8803,8471,10231,11229
292,Chhattisgarh,TOTAL CRIMES AGAINST WOMEN,3989,3538,3336,3763,3599,3757,3775,3962,4002,4176,4219,4228
293,Goa,TOTAL CRIMES AGAINST WOMEN,83,76,121,132,121,96,80,130,164,140,127,200
294,Gujarat,TOTAL CRIMES AGAINST WOMEN,5805,5373,5735,6211,6343,7279,8260,8616,8009,8148,8815,9561
295,Haryana,TOTAL CRIMES AGAINST WOMEN,3393,4385,4170,4276,4161,4617,4645,5142,5312,5562,5491,6002
296,Himachal Pradesh,TOTAL CRIMES AGAINST WOMEN,890,838,729,823,793,792,1018,979,954,1028,997,912
297,Jammu & Kashmir,TOTAL CRIMES AGAINST WOMEN,1656,2016,2164,2208,2144,2432,2521,2295,2624,2611,3146,3328
298,Jharkhand,TOTAL CRIMES AGAINST WOMEN,2229,2490,2488,2490,2544,2979,3317,3183,3021,3087,3132,4536
299,Karnataka,TOTAL CRIMES AGAINST WOMEN,6002,6170,5834,5423,6057,6084,6569,6891,7852,8807,9594,10366
300,Kerala,TOTAL CRIMES AGAINST WOMEN,5450,5829,5653,6483,6762,7554,7837,8117,8049,9463,11288,10930
301,Madhya Pradesh,TOTAL CRIMES AGAINST WOMEN,14549,15260,14547,15203,14529,14321,15370,14908,15827,16468,16599,16832
302,Maharashtra,TOTAL CRIMES AGAINST WOMEN,12524,11322,11273,12169,13370,14452,14924,15862,15048,15737,15728,16353
303,Manipur,TOTAL CRIMES AGAINST WOMEN,112,170,137,134,140,171,188,211,194,190,247,304
304,Meghalaya,TOTAL CRIMES AGAINST WOMEN,66,71,69,113,131,176,172,208,237,261,269,255
305,Mizoram,TOTAL CRIMES AGAINST WOMEN,126,154,147,91,95,125,151,162,150,170,167,199
306,Nagaland,TOTAL CRIMES AGAINST WOMEN,30,26,25,30,37,43,32,47,46,41,38,51
307,Odisha,TOTAL CRIMES AGAINST WOMEN,5357,4779,4946,5239,6249,6825,7304,8303,8120,8501,9433,11988
308,Punjab,TOTAL CRIMES AGAINST WOMEN,2361,2295,2375,1955,1969,2242,2694,2627,2631,2853,2641,3238
309,Rajasthan,TOTAL CRIMES AGAINST WOMEN,12175,12049,11812,13127,11657,12934,14270,14491,17316,18182,19888,21106
310,Sikkim,TOTAL CRIMES AGAINST WOMEN,24,28,37,49,62,47,55,48,41,42,55,68
311,Tamil Nadu,TOTAL CRIMES AGAINST WOMEN,10111,9798,8888,9332,8648,6489,7811,7220,6051,6708,6940,7192
312,Tripura,TOTAL CRIMES AGAINST WOMEN,438,536,537,670,840,964,1067,1416,1517,1678,1358,1559
313,Uttar Pradesh,TOTAL CRIMES AGAINST WOMEN,20227,15647,12840,15485,14875,16375,20993,23569,23254,20169,22639,23569
314,Uttarakhand,TOTAL CRIMES AGAINST WOMEN,749,870,886,988,786,1038,1097,1151,1188,1074,996,1067
315,West Bengal,TOTAL CRIMES AGAINST WOMEN,6570,6842,8508,11047,11887,12785,16544,20912,23307,26125,29133,30942
316,A&N Islands,TOTAL CRIMES AGAINST WOMEN,34,27,22,27,22,36,56,80,92,85,51,49
317,Chandigarh,TOTAL CRIMES AGAINST WOMEN,150,189,159,188,205,224,230,143,150,141,156,241
318,D&N Haveli,TOTAL CRIMES AGAINST WOMEN,19,15,13,22,24,32,18,28,20,30,18,16
319,Daman & Diu,TOTAL CRIMES AGAINST WOMEN,10,8,10,7,10,9,11,15,13,14,11,11
320,Delhi UT,TOTAL CRIMES AGAINST WOMEN,2291,2216,3282,3677,4351,4544,4804,3938,4251,4518,5234,5959
321,Lakshadweep,TOTAL CRIMES AGAINST WOMEN,0,2,4,1,0,1,5,4,1,1,0,2
322,Puducherry,TOTAL CRIMES AGAINST WOMEN,119,141,121,110,127,149,179,129,106,115,89,61
323,TOTAL Crime against Women,TOTAL CRIMES AGAINST WOMEN,143795,143034,140601,154333,155553,164765,185312,195857,203804,213585,228650,244270

# normalizind data for each year

In [282]:
data=pd.read_csv('data.csv')
femalePopulation=pd.read_csv('FemalePopulation.csv')
states=femalePopulation['STATE/UT']

for state in states:
    for year in range(2001,2013):
        data_each_state=data.loc[data['STATE/UT']== state][str(year)]
        population=femalePopulation.loc[femalePopulation['STATE/UT']==state ][str(year)]
        population=population.values[0]
        new_data_each_state=data_each_state/population * 100 # as population is in thousands
        index=new_data_each_state.index.values
        for i in index:
            data.loc[i,str(year)]=new_data_each_state.loc[i]
        
        
data.to_csv('normalised.csv')

In [284]:
data

,STATE/UT,CRIME HEAD,2001,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012
0,Andhra Pradesh,RAPE,2.311387,2.624479,2.446974,2.596540,2.361886,2.620142,2.643672,3.073350,2.875399,3.264308,3.423227,3.154033
1,Arunachal Pradesh,RAPE,6.370656,7.238095,5.827068,7.792208,6.410256,6.690778,8.571429,7.407407,10.296684,8.103448,7.155026,7.744108
2,Assam,RAPE,6.344153,7.410237,8.234321,8.673432,9.035177,8.948353,10.192212,10.060165,11.259147,11.725031,11.432414,11.393666
3,Bihar,RAPE,2.233681,2.564861,2.383372,3.302133,2.676967,2.826596,3.509207,2.891727,2.031756,1.713030,1.983857,1.941849
4,Chhattisgarh,RAPE,9.256757,9.408194,8.372960,8.888277,8.938245,8.845231,8.599702,8.440494,8.304263,8.492070,8.716166,8.444953
5,Goa,RAPE,1.818182,1.823708,4.654655,5.441176,2.869440,2.932961,2.713704,3.931848,5.941846,4.400978,3.448276,6.380510
6,Gujarat,RAPE,1.177682,1.081672,0.941139,1.331344,1.253676,1.350114,1.188417,1.387549,1.585326,1.474681,1.566962,1.667901
7,Haryana,RAPE,4.069114,3.619048,3.471334,3.725150,4.367598,5.657919,4.462326,5.671910,5.330151,6.260870,6.273000,5.628107
8,Himachal Pradesh,RAPE,4.147157,4.525933,4.113614,4.938670,4.501916,3.569172,4.970303,4.859177,5.610055,4.858791,5.057194,5.461056
9,Jammu & Kashmir,RAPE,3.533347,3.948992,4.268663,4.339172,3.937316,4.821601,5.470085,4.097287,4.369469,4.452926,4.965047,5.359038
10,Jharkhand,RAPE,4.341168,5.990679,5.259270,5.789627,5.382416,5.622405,5.925567,5.402267,4.841099,5.132121,5.132906,5.243446
11,Karnataka,RAPE,1.129007,1.109760,1.203870,1.077379,1.254113,1.444826,1.556309,1.573858,1.776242,2.022852,2.172280,2.099179
12,Kerala,RAPE,3.432480,3.021130,2.364946,2.856973,2.821890,3.519972,2.975706,3.276419,3.252777,3.605345,6.394035,5.718615
13,Madhya Pradesh,RAPE,9.863687,9.803323,9.105724,9.382853,9.359480,9.127246,9.309662,8.930852,8.966384,9.225472,9.864744,9.766460
14,Maharashtra,RAPE,2.801325,2.863557,2.644090,2.850044,3.124747,2.989179,2.849792,3.016399,2.831125,3.011016,3.160770,3.373136
15,Manipur,RAPE,1.867414,1.289134,1.636364,2.782765,2.214349,3.499563,1.728608,3.245090,2.613828,2.833333,4.365733,5.126119
16,Meghalaya,RAPE,2.274716,3.281520,3.410060,4.541632,5.232558,6.070550,6.645057,7.040000,8.853755,11.640625,10.030864,12.509535
17,Mizoram,RAPE,12.121212,17.471264,12.244898,4.474273,8.185841,15.720524,17.887931,16.382979,17.473684,19.126819,15.811088,20.892495
18,Nagaland,RAPE,1.802757,1.778243,1.446281,1.834862,1.711984,2.286282,1.275761,1.842871,2.107280,1.515152,2.151543,1.940850
19,Odisha,RAPE,4.354056,3.762592,3.902045,4.098143,4.206592,5.131277,4.841953,5.682630,5.172937,5.134499,5.519158,7.171667
20,Punjab,RAPE,2.620011,2.595486,3.257050,3.301168,3.327759,3.651685,4.238465,4.174067,4.079840,4.312456,3.744528,5.263158
21,Rajasthan,RAPE,3.872706,3.803423,3.725915,3.613200,3.392320,3.639596,4.079750,4.388380,4.836809,4.920908,5.549390,6.220778
22,Sikkim,RAPE,3.174603,2.352941,3.861004,1.145038,6.766917,7.434944,8.791209,7.246377,6.428571,6.338028,5.574913,11.683849
23,Tamil Nadu,RAPE,1.364296,1.705852,1.763049,1.939006,1.776492,1.410276,1.601445,1.741483,1.798431,2.055800,2.015361,2.179957
24,Tripura,RAPE,6.551060,6.844106,7.129456,9.876543,9.878049,11.378688,9.334126,11.978861,11.020882,13.646789,11.614731,12.821948
25,Uttar Pradesh,RAPE,2.490049,1.764097,1.113529,1.674438,1.430755,1.515693,1.865625,2.079143,1.919258,1.675044,2.150243,2.031713
26,Uttarakhand,RAPE,1.777564,2.102031,2.484905,2.627370,2.989436,3.252212,2.548464,1.866152,2.345731,2.519783,2.648327,2.996558
27,West Bengal,RAPE,1.831568,1.932822,2.517714,3.659777,4.133265,4.194533,5.046608,5.365865,5.482925,5.370796,5.437934,4.663354
28,A&N Islands,RAPE,1.840491,1.212121,1.183432,5.747126,2.209945,3.191489,1.530612,5.853659,8.372093,10.714286,5.579399,4.979253
29,Chandigarh,RAPE,4.568528,4.500000,4.368932,4.418605,7.333333,4.033970,4.444444,3.831418,5.272727,5.354059,4.455446,4.272152
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
294,Gujarat,TOTAL CRIMES AGAINST WOMEN,23.903644,21.767137,22.870474,24.392255,24.543414,27.761251,31.064310,31.965571,29.323033,29.450248,31.464163,33.714165
295,Haryana,TOTAL CRIMES AGAINST WOMEN,34.689705,43.959900,41.006982,41.266165,39.422075,42.964824,42.474396,46.220225,46.954831,48.365217,46.991870,50.568708
296,Himachal Pradesh,TOTAL CRIMES AGAINST WOMEN,29.765886,27.684176,23.800196,26.565526,25.319285,25.015793,31.822445,30.300217,29.245861,31.217735,30.012041,27.215756
297,Jammu & Kashmir,TOTAL CRIMES AGAINST WOMEN,34.622622,41.464418,43.779082,43.949045,41.998041,46.904532,47.882241,42.937325,48.377581,47.455471,56.390034,58.860983
298,Jharkhand,TOTAL CRIMES AGAINST WOMEN,17.066075,18.716176,18.377899,18.088043,18.184417,20.962635,22.988426,21.738833,20.340695,20.495286,20.505434,29.290972
299,Karnataka,TOTAL CRIMES AGAINST WOMEN,23.127312,23.449377,21.879688,20.077749,22.146252,21.975799,23.448153,24.317171,27.400893,30.401464,32.768632,35.040395
300,Kerala,TOTAL CRIMES AGAINST WOMEN,33.286508,35.290912,33.931573,38.586989,39.919712,44.242708,45.548065,46.821643,46.094376,53.812909,63.759602,61.339020
301,Madhya Pradesh,TOTAL CRIMES AGAINST WOMEN,50.335594,51.746355,48.378729,49.616527,46.553879,45.072861,47.538043,45.332360,47.335208,48.460950,48.075419,47.996806
302,Maharashtra,TOTAL CRIMES AGAINST WOMEN,26.946082,23.980175,23.506965,24.987167,27.040693,28.799745,29.311022,30.709957,28.727425,29.633744,29.225509,29.995048
303,Manipur,TOTAL CRIMES AGAINST WOMEN,10.457516,15.653775,12.454545,12.028725,12.400354,14.960630,16.248920,18.018787,16.357504,15.833333,20.345964,24.735557
304,Meghalaya,TOTAL CRIMES AGAINST WOMEN,5.774278,6.131261,5.882353,9.503785,10.880399,14.438064,13.938412,16.640000,18.735178,20.390625,20.756173,19.450801
305,Mizoram,TOTAL CRIMES AGAINST WOMEN,29.370629,35.402299,33.333333,20.357942,21.017699,27.292576,32.543103,34.468085,31.578947,35.343035,34.291581,40.365112
306,Nagaland,TOTAL CRIMES AGAINST WOMEN,3.181336,2.719665,2.582645,3.058104,3.726083,4.274354,3.140334,4.558681,4.406130,3.882576,3.554724,4.713494
307,Odisha,TOTAL CRIMES AGAINST WOMEN,29.524912,26.022325,26.620022,27.883336,32.899863,35.554282,37.663074,42.392525,41.059871,42.583780,46.818543,58.967044
308,Punjab,TOTAL CRIMES AGAINST WOMEN,20.757869,19.921875,20.356561,16.548163,16.463211,18.522802,22.000817,21.209430,21.005988,22.533765,20.645716,25.061920
309,Rajasthan,TOTAL CRIMES AGAINST WOMEN,44.947761,43.603662,41.914765,45.694096,39.823039,43.386669,47.025869,46.931373,55.137717,56.952232,61.314589,64.077965
310,Sikkim,TOTAL CRIMES AGAINST WOMEN,9.523810,10.980392,14.285714,18.702290,23.308271,17.472119,20.146520,17.391304,14.642857,14.788732,19.163763,23.367698
311,Tamil Nadu,TOTAL CRIMES AGAINST WOMEN,32.610869,31.299514,28.132814,29.279618,26.905606,20.024688,23.917570,21.943288,18.258902,20.102490,20.659681,21.273071
312,Tripura,TOTAL CRIMES AGAINST WOMEN,28.131021,33.967047,33.583490,41.358025,51.219512,58.037327,63.436385,83.147387,87.993039,96.215596,76.940510,87.290034
313,Uttar Pradesh,TOTAL CRIMES AGAINST WOMEN,25.723297,19.507299,15.694519,18.560247,17.487656,18.888492,23.765212,26.190979,25.372613,21.614815,23.839058,24.394005
314,Uttarakhand,TOTAL CRIMES AGAINST WOMEN,17.991833,20.547945,20.575941,22.572538,17.666891,22.964602,23.894576,24.688975,25.105664,22.365681,20.447547,21.603563
315,West Bengal,TOTAL CRIMES AGAINST WOMEN,16.972359,17.423413,21.377959,27.409870,29.141232,30.980421,39.644389,49.585052,54.704847,60.714867,67.043310,70.524684
316,A&N Islands,TOTAL CRIMES AGAINST WOMEN,20.858896,16.363636,13.017751,15.517241,12.154696,19.148936,28.571429,39.024390,42.790698,37.946429,21.888412,20.331950
317,Chandigarh,TOTAL CRIMES AGAINST WOMEN,38.071066,47.250000,38.592233,43.720930,45.555556,47.558386,46.464646,27.394636,27.272727,24.352332,25.742574,38.132911
318,D&N Haveli,TOTAL CRIMES AGAINST WOMEN,19.191919,15.957447,13.829787,22.680412,23.300971,29.357798,15.384615,22.047244,14.388489,20.000000,11.250000,9.467456
319,Daman & Diu,TOTAL CRIMES AGAINST WOMEN,15.151515,11.267606,13.333333,8.860759,12.195122,10.588235,12.500000,16.853933,14.285714,15.053763,11.578947,11.340206
320,Delhi UT,TOTAL CRIMES AGAINST WOMEN,36.697101,34.474175,49.637024,54.081483,62.246066,63.234066,65.041971,51.884058,54.513978,56.383377,63.557984,70.395747
321,Lakshadweep,TOTAL CRIMES AGAINST WOMEN,0.000000,6.250000,12.121212,2.941176,0.000000,2.777778,13.513514,10.810811,2.702703,2.631579,0.000000,5.128205
322,Puducherry,TOTAL CRIMES AGAINST WOMEN,24.435318,28.834356,24.297189,21.484375,24.007561,27.239488,31.569665,21.864407,17.235772,17.968750,13.464448,8.957416
323,TOTAL Crime against Women,TOTAL CRIMES AGAINST WOMEN,143795.000000,143034.000000,140601.000000,154333.000000,155553.000000,164765.000000,185312.000000,195857.000000,203804.000000,213585.000000,228650.000000,244270.000000

# splitting normalised.csv yearwise to DATA_perlakh_year.csv

In [382]:
data=pd.read_csv('normalised.csv')

states=list(['Andhra Pradesh','Arunachal Pradesh','Assam','Bihar','Chhattisgarh','Goa','Gujarat','Haryana','Himachal Pradesh','Jammu & Kashmir','Jharkhand','Karnataka','Kerala','Madhya Pradesh','Maharashtra','Manipur','Meghalaya','Mizoram','Nagaland','Odisha','Punjab','Rajasthan','Sikkim','Tamil Nadu','Tripura','Uttar Pradesh','Uttarakhand','West Bengal','A&N Islands','Chandigarh','D&N Haveli','Daman & Diu','Delhi UT','Lakshadweep','Puducherry','All India'])

for year in range(2001,2013):
    yy=str(year)
#     yy='2001'
    eachyear=data[['STATE/UT','CRIME HEAD',yy]]
    eachyear=eachyear.set_index('STATE/UT')    
    eachyear=eachyear.set_index('CRIME HEAD').groupby(level=0).apply(lambda x : np.concatenate(x.values.tolist())).apply(pd.Series)
    eachyear.columns=states

    eachyear=eachyear.T
    eachyear=eachyear.drop('All India')
    eachyear=eachyear.drop('TOTAL CRIMES AGAINST WOMEN',axis=1)
    eachyear
    eachyear.to_csv(('DATA_perlakh_'+yy+'.csv'))

    testdata=pd.read_csv(('DATA_perlakh_'+yy+'.csv'))
    testdata=testdata.rename(index=str,columns={'Unnamed: 0':'STATE/UT'})
    testdata.to_csv(('DATA_perlakh_'+yy+'.csv'),index=False)

# PCA for all years

In [383]:
for year in range(2001,2013):
    yy=str(year)
    datayear=pd.read_csv(('DATA_perlakh_'+ yy+'.csv'))
    states=datayear['STATE/UT']
    x=datayear.drop('STATE/UT',axis=1)
    features=list(x.columns)
    x = StandardScaler().fit_transform(x)
    pd.DataFrame(data=x,columns=features)
    pca = PCA(n_components=2)
    principalComponents = pca.fit_transform(x)
    principalDf = pd.DataFrame(data = principalComponents, columns = ['principal component 1', 'principal component 2'])
    principalDf.insert(loc=0,column='STATE/UT',value=datayear['STATE/UT'],)
    principalDf.to_csv(('principal_components_'+yy+'.csv'))